# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32
version:      0.27
version_from: Win32.pm
installdirs:  perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
