--- #YAML:1.0
name:                Win32-API
version:             0.47
abstract:            Perl Win32 API Import Facility
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Aldo Calpini <dada@perl.it>
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
