abstract: Comprehensive access to the Windows API.
author: Jan Dubois <jand@activestate.com>
distribution_type: module
installdirs: site
license: perl
name: libwin32
requires: 
  perl: 5.6
version: 0.28
version_from: Bundle/libwin32.pm
